import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import {
    Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer,
    BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Cell,
    PieChart, Pie
} from 'recharts';
import { ArrowLeft, ArrowRight, Brain, Target, AlertTriangle, ShieldCheck, Download, Code2, Sparkles } from 'lucide-react';
import { useTheme } from '../components/ThemeProvider';

// Mock Data
const skillRadar = [
    { subject: 'Algorithms', A: 80, b: 60, fullMark: 100 },
    { subject: 'Data Structs', A: 70, b: 85, fullMark: 100 },
    { subject: 'System Design', A: 45, b: 75, fullMark: 100 },
    { subject: 'Databases', A: 60, b: 80, fullMark: 100 },
    { subject: 'Networking', A: 50, b: 70, fullMark: 100 },
    { subject: 'OS Concepts', A: 90, b: 75, fullMark: 100 },
];

const shapData = [
    { feature: 'Coding Accuracy', impact: -0.35, color: '#f43f5e' }, // rose-500
    { feature: 'Time per Question', impact: -0.25, color: '#f43f5e' },
    { feature: 'Retry Attempts', impact: -0.15, color: '#f43f5e' },
    { feature: 'Quiz Score', impact: 0.10, color: '#10b981' }, // emerald-500
    { feature: 'Difficulty Lvl', impact: 0.20, color: '#10b981' },
];

export default function SkillGapReport() {
    const { isDark } = useTheme();

    const reportData = {
        gap_probability: 72, // Whole number for circle
        confidence_score: 85.0,
        weak_topic_detection: 'System Design',
        strong_topic: 'OS Concepts',
        recommendations: 'Focus on improving metrics related to system design. Practice more high-level architecture challenges under timed conditions. Your base OS knowledge is excellent, use that to understand hardware limitations.',
    };

    // Data for circular progress
    const gapData = [
        { name: 'Gap', value: reportData.gap_probability, fill: '#f59e0b' },
        { name: 'Remaining', value: 100 - reportData.gap_probability, fill: isDark ? '#1E293B' : '#E2E8F0' }
    ];

    return (
        <div className="min-h-screen bg-light-bg dark:bg-dark-bg pt-24 pb-12 transition-colors duration-300">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">

                {/* Navigation */}
                <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
                    <Link to="/student" className="inline-flex items-center text-sm font-bold text-light-muted dark:text-dark-muted hover:text-brand-600 dark:hover:text-brand-400 transition-colors group">
                        <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
                        Back to Dashboard
                    </Link>
                </motion.div>

                {/* Header */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 relative z-10">
                    <div>
                        <motion.h1
                            initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}
                            className="text-4xl font-extrabold text-light-text dark:text-dark-text tracking-tight flex items-center"
                        >
                            <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-brand-500 to-accent-500 flex items-center justify-center mr-4 shadow-glow">
                                <Brain className="w-6 h-6 text-white" />
                            </div>
                            Diagnostic <span className="text-gradient ml-2">Report</span>
                        </motion.h1>
                        <motion.p
                            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.1 }}
                            className="text-light-muted dark:text-dark-muted mt-4 text-lg max-w-2xl"
                        >
                            Comprehensive breakdown of your core abilities generated by our ML ensemble models.
                        </motion.p>
                    </div>
                    <motion.button
                        initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }}
                        className="btn-secondary flex items-center space-x-2"
                    >
                        <Download className="w-4 h-4" />
                        <span>Export Full PDF</span>
                    </motion.button>
                </div>

                {/* Top Highlights */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

                    <motion.div className="premium-card relative overflow-hidden group" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
                        <div className="absolute inset-0 bg-gradient-to-br from-amber-500/10 to-transparent dark:from-amber-500/5 group-hover:from-amber-500/20 transition-colors duration-500"></div>
                        <div className="p-6 relative z-10 flex items-center justify-between">
                            <div>
                                <h3 className="font-bold text-light-muted dark:text-dark-muted uppercase tracking-wider text-xs mb-2">Gap Probability</h3>
                                <div className="text-4xl font-black text-light-text dark:text-dark-text">{reportData.gap_probability}%</div>
                                <p className="text-sm font-semibold text-amber-600 dark:text-amber-500 mt-2 flex items-center">
                                    <AlertTriangle className="w-4 h-4 mr-1" /> Moderate Risk
                                </p>
                            </div>
                            <div className="w-24 h-24">
                                <ResponsiveContainer width="100%" height="100%">
                                    <PieChart>
                                        <Pie data={gapData} cx="50%" cy="50%" innerRadius={30} outerRadius={40} dataKey="value" startAngle={90} endAngle={-270} stroke="none" cornerRadius={10} />
                                    </PieChart>
                                </ResponsiveContainer>
                            </div>
                        </div>
                    </motion.div>

                    <motion.div className="premium-card relative overflow-hidden group" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
                        <div className="absolute inset-0 bg-gradient-to-br from-brand-500/10 to-transparent dark:from-brand-500/5 group-hover:from-brand-500/20 transition-colors duration-500"></div>
                        <div className="p-6 relative z-10">
                            <div className="flex justify-between items-start mb-4">
                                <h3 className="font-bold text-light-muted dark:text-dark-muted uppercase tracking-wider text-xs">Prediction Confidence</h3>
                                <Target className="w-5 h-5 text-brand-500" />
                            </div>
                            <div className="text-4xl font-black text-light-text dark:text-dark-text mb-2">{reportData.confidence_score}%</div>
                            <p className="text-sm font-medium text-light-muted dark:text-dark-muted mt-2">
                                Based on <span className="font-bold text-brand-600 dark:text-brand-400">12 exams</span> and code analytics.
                            </p>
                        </div>
                    </motion.div>

                    <motion.div className="premium-card relative overflow-hidden group" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
                        <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/10 to-transparent dark:from-emerald-500/5 group-hover:from-emerald-500/20 transition-colors duration-500"></div>
                        <div className="p-6 relative z-10">
                            <div className="flex justify-between items-start mb-4">
                                <h3 className="font-bold text-light-muted dark:text-dark-muted uppercase tracking-wider text-xs">Strongest Competency</h3>
                                <div className="w-8 h-8 rounded-full bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center">
                                    <ShieldCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
                                </div>
                            </div>
                            <div className="text-2xl xl:text-3xl font-black text-emerald-600 dark:text-emerald-400 mb-2 truncate" title={reportData.strong_topic}>
                                {reportData.strong_topic}
                            </div>
                            <p className="text-sm font-medium text-light-muted dark:text-dark-muted mt-2">
                                Top <span className="font-bold text-emerald-600 dark:text-emerald-400">15%</span> of platform users.
                            </p>
                        </div>
                    </motion.div>
                </div>

                {/* Main Charts area */}
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">

                    {/* Radar Chart */}
                    <motion.div className="premium-card p-6 flex flex-col" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.4 }}>
                        <h3 className="text-xl font-bold mb-2 text-light-text dark:text-dark-text">Competency Radar</h3>
                        <p className="text-sm font-medium text-light-muted dark:text-dark-muted mb-6">Comparison against cohort averages</p>
                        <div className="h-[350px] w-full mt-4 bg-slate-50/50 dark:bg-white/[0.02] rounded-2xl border border-light-border dark:border-white/5">
                            <ResponsiveContainer width="100%" height="100%">
                                <RadarChart cx="50%" cy="50%" outerRadius="70%" data={skillRadar} className="[&_.recharts-polar-grid-angle_line]:stroke-light-border dark:[&_.recharts-polar-grid-angle_line]:stroke-white/10 [&_.recharts-polar-grid-concentric_path]:stroke-light-border dark:[&_.recharts-polar-grid-concentric_path]:stroke-white/10">
                                    <PolarGrid stroke={isDark ? '#1E293B' : '#E2E8F0'} />
                                    <PolarAngleAxis dataKey="subject" tick={{ fill: isDark ? '#94A3B8' : '#64748B', fontSize: 13, fontWeight: 'bold' }} />
                                    <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                                    <Radar name="You" dataKey="A" stroke="#6366f1" fill="#6366f1" fillOpacity={0.6} strokeWidth={3} />
                                    <Radar name="Cohort Target" dataKey="b" stroke={isDark ? '#475569' : '#CBD5E1'} fill={isDark ? '#475569' : '#CBD5E1'} fillOpacity={0.2} strokeWidth={2} strokeDasharray="4 4" />
                                    <RechartsTooltip
                                        contentStyle={{ backgroundColor: isDark ? '#131A2A' : '#ffffff', border: isDark ? '1px solid #1E293B' : '1px solid #E2E8F0', borderRadius: '12px', color: isDark ? '#F8FAFC' : '#0F172A', boxShadow: '0 10px 40px -10px rgba(0,0,0,0.1)' }}
                                        itemStyle={{ fontWeight: 'bold' }}
                                    />
                                </RadarChart>
                            </ResponsiveContainer>
                        </div>
                        {/* Legend inside panel */}
                        <div className="flex justify-center gap-6 mt-6">
                            <div className="flex items-center text-sm font-bold text-light-muted dark:text-dark-muted"><span className="w-3 h-3 rounded-md bg-brand-500 mr-2 shadow-sm"></span> You</div>
                            <div className="flex items-center text-sm font-bold text-light-muted dark:text-dark-muted"><span className="w-3 h-3 rounded-md bg-slate-400 dark:bg-slate-600 mr-2 border border-dashed border-slate-500"></span> Cohort Target</div>
                        </div>
                    </motion.div>

                    {/* SHAP Values Chart */}
                    <motion.div className="premium-card p-6 flex flex-col" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.5 }}>
                        <h3 className="text-xl font-bold mb-2 flex items-center text-light-text dark:text-dark-text">
                            Model Explainability
                            <span className="ml-3 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-widest bg-brand-50 text-brand-600 dark:bg-brand-900/30 dark:text-brand-400 border border-brand-200 dark:border-brand-800">SHAP</span>
                        </h3>
                        <p className="text-sm font-medium text-light-muted dark:text-dark-muted mb-6">Factors actively influencing your gap probability</p>

                        <div className="h-[350px] w-full mt-4">
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={shapData} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                                    <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke={isDark ? '#1E293B' : '#E2E8F0'} />
                                    <XAxis type="number" domain={[-0.5, 0.5]} axisLine={false} tickLine={false} tick={{ fill: isDark ? '#64748B' : '#94A3B8' }} />
                                    <YAxis type="category" dataKey="feature" axisLine={false} tickLine={false} tick={{ fill: isDark ? '#64748B' : '#64748B', fontSize: 12, fontWeight: 'bold' }} />
                                    <RechartsTooltip
                                        cursor={{ fill: isDark ? '#1E293B' : '#F1F5F9', opacity: 0.5 }}
                                        contentStyle={{ backgroundColor: isDark ? '#131A2A' : '#ffffff', border: isDark ? '1px solid #1E293B' : '1px solid #E2E8F0', borderRadius: '12px' }}
                                        formatter={(val) => val.toFixed(3)}
                                    />
                                    <Bar dataKey="impact" radius={[4, 4, 4, 4]} barSize={16}>
                                        {shapData.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={entry.color} />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                        <div className="flex justify-between text-xs font-bold uppercase tracking-wider text-light-muted dark:text-dark-muted mt-6 px-4 py-3 bg-slate-50 dark:bg-white/5 rounded-xl border border-light-border dark:border-white/5">
                            <span className="flex items-center"><span className="w-2.5 h-2.5 rounded-sm bg-rose-500 mr-2" /> Widens Gap (- impact)</span>
                            <span className="flex items-center"><span className="w-2.5 h-2.5 rounded-sm bg-emerald-500 mr-2" /> Closes Gap (+ impact)</span>
                        </div>
                    </motion.div>
                </div>

                {/* Recommendation Block */}
                <motion.div className="relative overflow-hidden premium-card p-8 border-l-4 border-l-brand-500" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.6 }}>
                    {/* Subtle bg glow */}
                    <div className="absolute -left-10 -bottom-10 w-64 h-64 bg-brand-500/5 dark:bg-brand-500/10 rounded-full blur-3xl"></div>

                    <div className="relative z-10">
                        <h3 className="text-2xl font-extrabold text-light-text dark:text-dark-text flex items-center mb-4">
                            <Sparkles className="w-6 h-6 mr-3 text-brand-500" />
                            AI Action Plan
                        </h3>
                        <p className="text-lg text-slate-700 dark:text-slate-300 leading-relaxed mb-8 max-w-4xl font-medium">
                            {reportData.recommendations}
                        </p>

                        <div className="flex flex-wrap gap-4">
                            <Link to="/courses" className="btn-primary block text-center shadow-glow">
                                View System Design Path
                            </Link>
                            <button className="btn-secondary group">
                                Attempt Review Sandbox <ArrowRight className="inline w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
                            </button>
                        </div>
                    </div>
                </motion.div>

            </div>
        </div>
    );
}
