# Generated by Django 5.2.11 on 2026-07-13 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chathistory_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('report_data', models.JSONField(default=dict)),
                ('rewritten_resumes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
